global using MediatR;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.EntityFrameworkCore;
global using PageManager.Application.DI;
global using PageManager.Application.Features.Pages.ArchiveAndMayPublishFeature;
global using PageManager.Application.Features.Pages.GetPublishedPage;
global using PageManager.Infrastructure.DI;
global using PageManager.Infrastructure.Persistence;
global using PageManager.Shared.Exceptions;
global using Serilog;
global using ValidationException = FluentValidation.ValidationException;